### PR TITLE
Routes for Users and Types

### PR DESCRIPTION
**Pull request by marmelendez**
- Fix relation 1:N between Users and Types (user has one type, type has many users)
- Implement routes for Users
- Implement routes for Types

### CODE REVIEW

**Review by proxyz100 — COMMENTED** [review]
I think it is great! :)

**Review by AlmaLSt — APPROVED** [review]
Everything seems good to me, great job!

**Review by francisco-solis99 — CHANGES_REQUESTED** [review]
It looks great😁, but we have to change the base branch from "dev" to "feat/routes" to make the PR. I'm going to resolve all the possible conflicts right there in the feat/routes branch before we send it to the dev branch. And great job with login and sign-up endpoints 👌

**Review by francisco-solis99 — APPROVED** [review]
Awesome!

**Pull request merged**
