### PR TITLE
Feat/routes

### PR DESCRIPTION
**Pull request by francisco-solis99**
- Join all the entities routes
- Add dotenv and jsonwebtoken as dependencies to sign-up and login users
- Add the favorites routes
- Add the init of database with sequelize
- Change the types of some properties in some entities

### CODE REVIEW

**Review by proxyz100 — COMMENTED** [review]
Great job! :)

**Review by AlmaLSt — APPROVED** [review]
Everything looks good to me 👍

**Review by AlmaLSt — APPROVED** [review]
Everything looks good to me 👍

**Review by proxyz100 — APPROVED** [review]
Looks great! Good job!

**Pull request merged**
